manifest:
  remotes:
    - name: zmkfirmware
      url-base: https://github.com/zmkfirmware
    - name: ftc
      url-base: https://github.com/ftc
    - name: StMotorSpark
      url-base: https://github.com/StMotorSpark
    - name: mouse-dv
      url-base: https://github.com/digver
  projects:
    - name: zmk
      remote: mouse-dv
      revision: mouse-ftc-aurora-sweep
      import: app/west.yml
  self:
    path: config
